# Bloom - Predictive Analytics Tool for Fertility Treatment {#Bloom}

#### Keywords {-}

Bio-informatics, Genomics, Predictive analytics, Fertility Treatment

## Problem  

Problem

To put the fertility process in perspective, two letters is all it takes to create life, ‘x’ and ‘y’... but wish life was that simple. Infertility is a global issue, even advancements in the field of medicine and science has not made a significant change in the last 10 years. Female infertility rate in the US was last recorded at 12.1% out of which 99% of women have undergone infertility treatments (https://www.cdc.gov/nchs/fastats/infertility.htm ). The US Fertility Treatment market is expected to be valued at USD 6 Billion and global market at USD 20 Billion by the end of 2020. US holds 1/3rd of the Global Market Share in the Fertility Treatment sector and may very well be tagged as an industry. Growing cost of fertility treatments not just take a toll on the patients financially, but also on their emotional well-being owing to the uncertainty of treatment outcome. Centers offering fertility treatments give very little information on what else patients could do before spending on treatments.

My goal is to present a solution which will be a self-help tool for patients and treatment tool for providers which would:
a.	Explore all preliminary tests to be completed prior to starting fertility treatments
b.	Based on predictive models created from test results, provide comprehensible suggestions on the best course of treatments and their success rate

## Solution

There are few products in the market currently however, they only focus on predicting the outcome of fertility treatment, which is objective and hardly understands the impact of such predictions on the patients should the predictions not be in favor. With advancements in science and the field of fertility, there are various tests and preliminary treatments that can be performed before a patient chooses to go through fertility treatment. It is easier for a patient to be convinced of the results once they have tried all possible options and move on than go through the financial and emotional drain.

The goal is to design an App which will collect extensive data from users, not limited to : Genetics, Age, Race, Ethnic origin, demographic information (where they were born, where they grew up, where they live now: this is a key piece of information which will help determine external factors such as climate, environment they may have been exposed to), occupation (to determine physical and emotional stress levels). Besides the the extensive Blood tests which tests a patient more for hormone imbalances, my discovery process will include few simple tests which is often not tested for. Once all Data has been compiled, the system will start an auto-elimination process based on Machine Language Technique to compare various reasons that has caused infertility in the male or female.

While the field of medicine captures data pertaining to science behind the reasons of infertility in men or women, my software will have the ability to build models which includes non-medical data to identify few causes for infertility.

The program will use data captured from the patient and compare it with available data from the Neural Network of World Wide Fertility Centers (NNWWFC) to build predictive models for outcome of various fertility treatments. AI bot will continue to analyze and perfect the predictive model as it continues to collect data (consent will be acquired) from Patients. Based on all computations, Patients will be presented with a holistic picture on the possible conditions that may have caused infertility, a list of preliminary treatments before undertaking actual procedure, any immediate changes to lifestyle (diet, exercise) and to present themselves for the actual procedure. By this time the predictive model would have given the best possible options for them including data to support success rates or in some cases prepare them for the outcome which may not be favorable. 
Various parameters will be taken into consideration to understand the patient and their partner’s medical history, family history and fed into the software.

An algorithm will then check to see if it has all the values required to feed the data to the next step. For any missing values, a custom test order will be generated to obtain further information. 

Once all values have been fed into the software, it will compare this data against patients with similar ethnicity, age group and their outcome to provide a preliminary report on the success rates with past data. A neural network of fertility centers across the country will help increase the data sample size 3.The system will then look for areas that may need preliminary treatment, this could range from simple changes in lifestyle such as diets, exercise and supplements to more complex treatments such as Hormone therapies which could increase the chances of a successful pregnancy. System will provide a custom test order to see if there are changes in values based on which patients will be cleared for next level of treatment 4.Most fertility clinics have the patients start with an IUI and then proceed to an IVF. While IUI is far cheaper, IVF is quite expensive. Insurance companies hardly cover such fertility treatments but those which do cover, expect the patients complete few cycles of IUI before authorizing IVF. For most patients their biological clock is ticking and they may not be a suitable candidate for IUI. Data Analysis can help provide data to insurance companies with complete profile on what the success rates are and why there should be an exception made in the patient’s case. The same Data can also help selfpay patients to choose or skip few preliminary treatments before signing up for IVF.

## Next steps
The tool continues to collect data from patients who are undergoing treatments to keep perfecting its model for suggestive / customized treatments. Over a period of time, the tool would have matured to provide closest to accurate results in outcome of treatment, retention of pregnancy and a healthy baby.

